### ISSUE TITLE
Getting Wheel error for command pip install vcf2fhir

### ISSUE THREAD

**Issue by pankajsurti** [elimuinformatics/vcf2fhir#109]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version:
* Operating System:

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

C:\SRC\vcf2fhir\vcf2fhir\test>pip install vcf2fhir
Collecting vcf2fhir
  Using cached vcf2fhir-0.1.1-py3-none-any.whl (26 kB)
Collecting PyVCF3>=1.0.3
  Using cached PyVCF3-1.0.3.tar.gz (977 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Cython>=0.29.21 in c:\users\XYZUser\appdata\local\programs\python\python310\lib\site-packages (from vcf2fhir) (0.29.34)
Collecting pyranges>=0.0.96
  Using cached pyranges-0.0.120.tar.gz (687 kB)
  Preparing metadata (setup.py) ... done
Collecting pandas
  Using cached pandas-2.0.0-cp310-cp310-win_amd64.whl (11.2 MB)
Collecting pysam
  Using cached pysam-0.21.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\XYZUser\AppData\Local\Temp\pip-build-env-s85ck20c\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\XYZUser\AppData\Local\Temp\pip-build-env-s85ck20c\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\XYZUser\AppData\Local\Temp\pip-build-env-s85ck20c\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\XYZUser\AppData\Local\Temp\pip-build-env-s85ck20c\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 383, in <module>
        File "<string>", line 79, in run_make_print_config
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\XYZUser\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\SRC\vcf2fhir\vcf2fhir\test>

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Did "pip install cython wheel" 
2. failed on vcf2fhir pip install

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by rhdolin** [comment]
Hi @pankajsurti , can you please take a look at https://github.com/elimuinformatics/vcf2fhir/issues/70 and see if that answers your issue? Are you running on Windows? If so, can you try running on Ubuntu?

**Comment by pankajsurti** [comment]
Ok, Thank you. I ran it on windows. I will try on Ubuntu and report.

**Comment by pankajsurti** [comment]
I used the link below to run Ubuntu on Windows and got both the first two install commands working. Thank you @rhdolin.

https://pbpython.com/wsl-python.html
